# Generated by Django 3.1.6 on 2021-04-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_tel', models.CharField(max_length=100, null=True)),
                ('client_name', models.CharField(max_length=100, null=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('barber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.barber')),
                ('tm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.time')),
            ],
        ),
        migrations.AddField(
            model_name='barber',
            name='time',
            field=models.ManyToManyField(to='main.Time'),
        ),
    ]
