# Generated by Django 3.1.6 on 2021-04-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='time',
            field=models.ManyToManyField(blank=True, null=True, to='main.Time'),
        ),
    ]
