# Generated by Django 3.1.6 on 2021-04-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210410_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='barber',
        ),
        migrations.AddField(
            model_name='order',
            name='barber',
            field=models.ManyToManyField(to='main.Barber'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='tm',
        ),
        migrations.AddField(
            model_name='order',
            name='tm',
            field=models.ManyToManyField(to='main.Time'),
        ),
    ]
