# Generated by Django 3.1.6 on 2021-04-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210428_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='time',
            field=models.ManyToManyField(blank=True, to='main.Time'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='barber',
        ),
        migrations.AddField(
            model_name='order',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.barber'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='tm',
        ),
        migrations.AddField(
            model_name='order',
            name='tm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.time'),
        ),
    ]
