# Generated by Django 3.1.6 on 2021-04-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210428_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tm',
        ),
    ]
