# Generated by Django 3.1.6 on 2021-04-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_order_tm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.time'),
        ),
    ]
